services:
  app:
    image: gik986/remoteprintcore-v2:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Europe/Sofia
    ports:
      - 8080:8080
    volumes:
      - sqlite_data:/app/data
      - uploads:/app/wwwroot/uploads
      - logs:/app/logs

volumes:
  sqlite_data:
  uploads:
  logs:
